language: objective-c
osx_image: xcode7
podfile: ./CI-HelloWorld/Podfile
xcode_workspace: CI-HelloWorld.xcworkspace
xcode_scheme: CI-HelloWorld

install:
    - pwd
    - cd CI-HelloWorld
    - pod install
